config/routes.rb
Rails.application.routes.draw do

  resources :searchpasswords
  resources :bjlogins
  resources :teamsets
  resources :timesets
  resources :qinmisets
  resources :shouyes
  resources :personals
  resources :commons
  
  resources :regist1s
  
  resources :users 

  root 'commons#index'

end

app/models/bjlogin.rb
class Bjlogin < ActiveRecord::Base
end

app/models/common.rb
class Common < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/qinmiset.rb
class Qinmiset < ActiveRecord::Base
end

app/models/regist1.rb
class Regist1 < ActiveRecord::Base
end

app/models/searchpassword.rb
class Searchpassword < ActiveRecord::Base
end

app/models/shouye.rb
class Shouye < ActiveRecord::Base
end

app/models/teamset.rb
class Teamset < ActiveRecord::Base
end

app/models/timeset.rb
class Timeset < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/bjlogins_controller.rb
class BjloginsController < ApplicationController
  before_action :set_bjlogin, only: [:show, :edit, :update, :destroy]

  # GET /bjlogins
  # GET /bjlogins.json
  def index
    @bjlogins = Bjlogin.all
  end

  # GET /bjlogins/1
  # GET /bjlogins/1.json
  def show
  end

  # GET /bjlogins/new
  def new
    @bjlogin = Bjlogin.new
  end

  # GET /bjlogins/1/edit
  def edit
  end

  # POST /bjlogins
  # POST /bjlogins.json
  def create
    @bjlogin = Bjlogin.new(bjlogin_params)

    respond_to do |format|
      if @bjlogin.save
        format.html { redirect_to @bjlogin, notice: 'Bjlogin was successfully created.' }
        format.json { render :show, status: :created, location: @bjlogin }
      else
        format.html { render :new }
        format.json { render json: @bjlogin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bjlogins/1
  # PATCH/PUT /bjlogins/1.json
  def update
    respond_to do |format|
      if @bjlogin.update(bjlogin_params)
        format.html { redirect_to @bjlogin, notice: 'Bjlogin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bjlogin }
      else
        format.html { render :edit }
        format.json { render json: @bjlogin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bjlogins/1
  # DELETE /bjlogins/1.json
  def destroy
    @bjlogin.destroy
    respond_to do |format|
      format.html { redirect_to bjlogins_url, notice: 'Bjlogin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bjlogin
      @bjlogin = Bjlogin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bjlogin_params
      params.fetch(:bjlogin, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :password, :email, :flag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bjlogins_helper.rb
module BjloginsHelper
end

app/helpers/commons_helper.rb
module CommonsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/qinmisets_helper.rb
module QinmisetsHelper
end

app/helpers/regist_1s_helper.rb
module Regist1sHelper
end

app/helpers/shouyes_helper.rb
module ShouyesHelper
end

app/helpers/teamsets_helper.rb
module TeamsetsHelper
end

app/helpers/timesets_helper.rb
module TimesetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bjlogins/_form.html.erb
<%= form_for(@bjlogin) do |f| %>
  <% if @bjlogin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bjlogin.errors.count, "error") %> prohibited this bjlogin from being saved:</h2>

      <ul>
      <% @bjlogin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bjlogins/edit.html.erb
<h1>Editing Bjlogin</h1>

<%= render 'form' %>

<%= link_to 'Show', @bjlogin %> |
<%= link_to 'Back', bjlogins_path %>

app/views/bjlogins/index.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>绑定手机</title>
    <!--<link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="css/bangding.css">
    <script type="text/javascript" src="./js/jquery-1.12.1.min.js"></script>
    <script type="text/javascript" src="./js/bootstrap.min.js"></script>
    <script type="text/javascript" src="./js/index.js"></script>
    <script type="text/javascript" src="./js/jianplaceholder.js"></script>
    <script type="text/javascript" src="./js/mobilenum.js"></script>
    <script type="text/javascript" src="js/appjs/layout.js" ></script>
    <!--<script type="text/javascript" src="js/appjs/Timetrans.js" ></script>-->
   <!-- <script type="text/javascript" src="js/appjs/layout.js" ></script>
    <script type="text/javascript" src="js/appjs/send.js" ></script>-->
  
    <%= stylesheet_link_tag "common" %>
    <%= stylesheet_link_tag "bootstrap.min" %> 
    <%= stylesheet_link_tag "index" %> 
    <%= stylesheet_link_tag "bangding" %>
    <%= javascript_include_tag "jquery-1.12.1.min" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "index" %>
    <%= javascript_include_tag "jianplaceholder" %>
    <%= javascript_include_tag "mobilenum.js" %>
    <%= javascript_include_tag "appjs/layout.js" %>
    <%= javascript_include_tag "appjs/layout.js" %>
    <%= javascript_include_tag "appjs/send.js" %>

</head>
<body ng-app="bind" ng-controller="bindcontroller">
    <div class="bangding">
        <div class="shouji">绑定手机:</div>
        <div class="bang">
            <span>手机号码：</span>
            <input type="text" placeholder="11位中国大陆手机号" id="mobilenum" ng-model="phone"/>
        </div>
        <div class="bang">
            <span>短信验证码：</span>
            <input type="text" placeholder="短信验证码" style="width: 240px" ng-model="codes"/>
            <button id="obtainnum" ng-click="send()">获取验证码</button>
        </div>
        <button class="determine" ng-click="queding()">确定</button>
    </div>
</body>
<!--<script type="text/javascript" src="js/appjs/layout.js" ></script>
<!--<script type="text/javascript" src="js/appjs/Timetrans.js" ></script>-->
<!--<script type="text/javascript" src="js/angular-1.5.8.js" ></script>
<script type="text/javascript" src="js/appjs/send.js" ></script>-->-->
</html>

app/views/bjlogins/new.html.erb
<h1>New Bjlogin</h1>

<%= render 'form' %>

<%= link_to 'Back', bjlogins_path %>

app/views/bjlogins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bjlogin_path(@bjlogin) %> |
<%= link_to 'Back', bjlogins_path %>