config/routes.rb
Rails.application.routes.draw do

  resources :searchpasswords
  resources :bjlogins
  resources :teamsets
  resources :timesets
  resources :qinmisets
  resources :shouyes
  resources :personals
  resources :commons
  
  resources :regist1s
  
  resources :users 

  root 'commons#index'

end

app/models/bjlogin.rb
class Bjlogin < ActiveRecord::Base
end

app/models/common.rb
class Common < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/qinmiset.rb
class Qinmiset < ActiveRecord::Base
end

app/models/regist1.rb
class Regist1 < ActiveRecord::Base
end

app/models/searchpassword.rb
class Searchpassword < ActiveRecord::Base
end

app/models/shouye.rb
class Shouye < ActiveRecord::Base
end

app/models/teamset.rb
class Teamset < ActiveRecord::Base
end

app/models/timeset.rb
class Timeset < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/searchpasswords_controller.rb
class SearchpasswordsController < ApplicationController
  before_action :set_searchpassword, only: [:show, :edit, :update, :destroy]

  # GET /searchpasswords
  # GET /searchpasswords.json
  def index
    @searchpasswords = Searchpassword.all
  end

  # GET /searchpasswords/1
  # GET /searchpasswords/1.json
  def show
  end

  # GET /searchpasswords/new
  def new
    @searchpassword = Searchpassword.new
  end

  # GET /searchpasswords/1/edit
  def edit
  end

  # POST /searchpasswords
  # POST /searchpasswords.json
  def create
    @searchpassword = Searchpassword.new(searchpassword_params)

    respond_to do |format|
      if @searchpassword.save
        format.html { redirect_to @searchpassword, notice: 'Searchpassword was successfully created.' }
        format.json { render :show, status: :created, location: @searchpassword }
      else
        format.html { render :new }
        format.json { render json: @searchpassword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searchpasswords/1
  # PATCH/PUT /searchpasswords/1.json
  def update
    respond_to do |format|
      if @searchpassword.update(searchpassword_params)
        format.html { redirect_to @searchpassword, notice: 'Searchpassword was successfully updated.' }
        format.json { render :show, status: :ok, location: @searchpassword }
      else
        format.html { render :edit }
        format.json { render json: @searchpassword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searchpasswords/1
  # DELETE /searchpasswords/1.json
  def destroy
    @searchpassword.destroy
    respond_to do |format|
      format.html { redirect_to searchpasswords_url, notice: 'Searchpassword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_searchpassword
      @searchpassword = Searchpassword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def searchpassword_params
      params.fetch(:searchpassword, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bjlogins_helper.rb
module BjloginsHelper
end

app/helpers/commons_helper.rb
module CommonsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/qinmisets_helper.rb
module QinmisetsHelper
end

app/helpers/regist_1s_helper.rb
module Regist1sHelper
end

app/helpers/searchpasswords_helper.rb
module SearchpasswordsHelper
end

app/helpers/shouyes_helper.rb
module ShouyesHelper
end

app/helpers/teamsets_helper.rb
module TeamsetsHelper
end

app/helpers/timesets_helper.rb
module TimesetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searchpasswords/_form.html.erb
<%= form_for(@searchpassword) do |f| %>
  <% if @searchpassword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@searchpassword.errors.count, "error") %> prohibited this searchpassword from being saved:</h2>

      <ul>
      <% @searchpassword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searchpasswords/edit.html.erb
<h1>Editing Searchpassword</h1>

<%= render 'form' %>

<%= link_to 'Show', @searchpassword %> |
<%= link_to 'Back', searchpasswords_path %>

app/views/searchpasswords/index.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>找回密码</title>
    <!--<link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="css/bangding.css">
    <script src="./js/jquery-1.12.1.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/index.js"></script>
    <script src="./js/jianplaceholder.js"></script>
    <script src="./js/mobilenum.js"></script>
    <script type="text/javascript" src="js/angular-1.5.8.min.js" ></script>
    <script type="text/javascript" src="js/appjs/layout.js" ></script>
    <script type="text/javascript" src="js/appjs/searchpassword.js" ></script>-->
     <%= stylesheet_link_tag "common" %>
    <%= stylesheet_link_tag "bootstrap.min" %> 
    <%= stylesheet_link_tag "index" %> 
    <%= stylesheet_link_tag "bangding" %>
    <%= javascript_include_tag "jquery-1.12.1.min" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "index" %>
    <%= javascript_include_tag "jianplaceholder" %>
    <%= javascript_include_tag "mobilenum.js" %>
    <%= javascript_include_tag "angular-1.5.8.min.js" %>
    <%= javascript_include_tag "appjs/layout.js" %>
    <%= javascript_include_tag "appjs/searchpassword.js" %>
    
</head>
<body ng-app="searchpassword_app" ng-controller="searchpassword_controller">
    <div class="bangding">
        <div class="shouji">找回密码:</div>
        <div class="bang">
            <span>手机号码：</span>
            <input type="text" placeholder="11位中国大陆手机号" id="mobilenum" class="reset_phone"/>
        </div>
        <div class="bang">
            <span>短信验证码：</span>
            <input type="text" placeholder="短信验证码" style="width: 240px" class="reset_message"/>
            <button id="obtainnum" ng-click="message()">获取验证码</button>
        </div>
        <div class="bang">
            <span>新密码：</span>
            <input type="password" class="reset_password" placeholder="请输入新密码"/>
        </div>
        <div class="bang">
            <span>确认新密码：</span>
            <input type="password" placeholder="请重新输入新密码" class="reset_password_ok"/>
        </div>
        <button class="determine" ng-click="resetpassword()">确定</button>
    </div>

</body> 
</html>

app/views/searchpasswords/new.html.erb
<h1>New Searchpassword</h1>

<%= render 'form' %>

<%= link_to 'Back', searchpasswords_path %>

app/views/searchpasswords/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_searchpassword_path(@searchpassword) %> |
<%= link_to 'Back', searchpasswords_path %>